from django.contrib import admin
from django.urls import path
from . import views

urlpatterns=[
    path("inventoryMenu", views.inventoryMenu),
    path("newInventoryItem", views.newInventoryItem),
    path("outputInventoryItem", views.outputInventoryItem),
    path("addCurrentInventoryItem", views.addCurrentInventoryItem),
    path("addNewInventoryItem", views.addNewInventoryItem),
    path("retrieveInventoryItem", views.retrieveInventoryItem),
    path("alterInventoryItem", views.alterInventoryItem),
    path("alterInventoryQuantity", views.alterInventoryQuantity),
    path("commitAlteredInventoryItem", views.commitAlteredInventoryItem),
    path("deleteCurrentInventoryItem", views.deleteCurrentInventoryItem),
    path("deleteSelectedInventoryItem", views.deleteSelectedInventoryItem),
    path("userMenu", views.userMenu),
    path("newUser", views.newUser),
    path("outputUser", views.outputUser),
    path("addCurrentUser", views.addCurrentUser),
    path("addNewUser", views.addNewUser),
    path("retrieveUser", views.retrieveUser),
    path("updateUserInfo", views.updateUserInfo),
    path("commitUpdatedInfo", views.commitUpdatedInfo),
    path("resetPassword", views.resetPassword),
    path("commitResetPassword", views.commitResetPassword),
    path("deleteCurrentUser", views.deleteCurrentUser),
    path("deleteSelectedUser", views.deleteSelectedUser),
    path("loginUser", views.loginUser),
    path("orderMenu", views.orderMenu),
    path("newOrder", views.newOrder),
    path("outputOrder", views.outputOrder),
    path("retrieveOrder", views.retrieveOrder),
    path("setAddress", views.setAddress),
    path("setPaymentMethod", views.setPaymentMethod),
    path("addItem", views.addItem),
    path("addItemWithID", views.addItemWithID),
    path("removeItem", views.removeItem),
    path("removeItemWithID", views.removeItemWithID),
    path("changeItemQuantity", views.changeItemQuantity),
    path("changeItemQuantityWithID", views.changeItemQuantityWithID),
    path("finalizeOrder", views.finalizeOrder),
    path("deductInventory", views.deductInventory),
]