# Generated by Django 4.2 on 2023-04-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('inventoryName', models.CharField(max_length=80)),
                ('department', models.CharField(max_length=80)),
                ('inventoryPrice', models.FloatField()),
                ('inventoryQuantity', models.FloatField()),
                ('inventoryValue', models.FloatField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Inventory',
                'ordering': ('-added',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('loginPassword', models.CharField(max_length=40)),
                ('creditCard', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('creditCard', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('items', models.CharField(max_length=255)),
                ('pricePerItem', models.CharField(max_length=255)),
                ('quantityPerItem', models.CharField(max_length=255)),
                ('costPerItem', models.CharField(max_length=255)),
                ('originalQuantityPerItem', models.CharField(max_length=255)),
                ('originalValuePerItem', models.CharField(max_length=255)),
                ('alteredQuantityPerItem', models.CharField(max_length=255)),
                ('alteredValuePerItem', models.CharField(max_length=255)),
                ('totalCost', models.FloatField()),
                ('orderDate', models.DateField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.users')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
    ]
